import type { Sticker } from '../types';

/**
 * Auto-generated sticker index
 * Run 'npm run index-stickers' to regenerate this file
 * 
 * Total: 154 stickers across 13 companies
 */

export const AVAILABLE_STICKERS: Sticker[] = [
  { id: 'aurora-usa-stiker-1', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0000_Capa-2.png', name: 'aurora usa stiker 1', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-2', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0001_Capa-3.png', name: 'aurora usa stiker 2', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-3', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0002_Capa-4.png', name: 'aurora usa stiker 3', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-4', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0003_Capa-5.png', name: 'aurora usa stiker 4', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-5', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0004_Capa-6.png', name: 'aurora usa stiker 5', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-6', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0005_Capa-7.png', name: 'aurora usa stiker 6', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-7', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0006_Capa-8.png', name: 'aurora usa stiker 7', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-8', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0007_Capa-9.png', name: 'aurora usa stiker 8', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-9', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0008_Capa-10.png', name: 'aurora usa stiker 9', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-10', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0009_Capa-11.png', name: 'aurora usa stiker 10', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-11', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0010_Capa-12.png', name: 'aurora usa stiker 11', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-12', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0011_Capa-13.png', name: 'aurora usa stiker 12', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'aurora-usa-stiker-13', icon: '/stickers/aurora usa stiker/aurora-usa-stiker_0012_Capa-1.png', name: 'aurora usa stiker 13', color: '#87CEEB', company: 'aurora usa stiker' },
  { id: 'auroraglobal-1', icon: '/stickers/AuroraGlobal/aurorra-global-_0000_Capa-2.png', name: 'Aurora Global 1', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroraglobal-2', icon: '/stickers/AuroraGlobal/aurorra-global-_0001_Capa-3.png', name: 'Aurora Global 2', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroraglobal-3', icon: '/stickers/AuroraGlobal/aurorra-global-_0002_Capa-4.png', name: 'Aurora Global 3', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroraglobal-4', icon: '/stickers/AuroraGlobal/aurorra-global-_0003_Capa-5.png', name: 'Aurora Global 4', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroraglobal-5', icon: '/stickers/AuroraGlobal/aurorra-global-_0004_Capa-6.png', name: 'Aurora Global 5', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroraglobal-6', icon: '/stickers/AuroraGlobal/aurorra-global-_0005_Capa-1.png', name: 'Aurora Global 6', color: '#FF6B35', company: 'Aurora Global' },
  { id: 'auroralogistic-1', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0000_Capa-1.png', name: 'Aurora Logistic 1', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-2', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0001_Capa-2.png', name: 'Aurora Logistic 2', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-3', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0002_Capa-3.png', name: 'Aurora Logistic 3', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-4', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0003_Capa-4.png', name: 'Aurora Logistic 4', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-5', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0004_Capa-5.png', name: 'Aurora Logistic 5', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-6', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0005_Capa-6.png', name: 'Aurora Logistic 6', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-7', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0006_Capa-7.png', name: 'Aurora Logistic 7', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-8', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0007_Capa-8.png', name: 'Aurora Logistic 8', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-9', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0008_Capa-9.png', name: 'Aurora Logistic 9', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-10', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0009_Capa-10.png', name: 'Aurora Logistic 10', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-11', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0010_Capa-11.png', name: 'Aurora Logistic 11', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-12', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0011_Capa-12.png', name: 'Aurora Logistic 12', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroralogistic-13', icon: '/stickers/AuroraLogistic/Aurora-logistic-stikel_0012_Capa-0.png', name: 'Aurora Logistic 13', color: '#00A9E0', company: 'Aurora Logistic' },
  { id: 'auroratabaco-1', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0000_Capa-1.png', name: 'Aurora Tabaco 1', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-2', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0001_Capa-2.png', name: 'Aurora Tabaco 2', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-3', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0002_Capa-3.png', name: 'Aurora Tabaco 3', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-4', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0003_Capa-4.png', name: 'Aurora Tabaco 4', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-5', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0004_Capa-5.png', name: 'Aurora Tabaco 5', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-6', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0005_Capa-6.png', name: 'Aurora Tabaco 6', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-7', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0006_Capa-7.png', name: 'Aurora Tabaco 7', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-8', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0007_Capa-8.png', name: 'Aurora Tabaco 8', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-9', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0008_Capa-9.png', name: 'Aurora Tabaco 9', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-10', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0009_Capa-10.png', name: 'Aurora Tabaco 10', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-11', icon: '/stickers/AuroraTabaco/LA-aurora-tabaco-stiker_0010_Capa-0.png', name: 'Aurora Tabaco 11', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-12', icon: '/stickers/AuroraTabaco/st1_0000_Layer-1.png', name: 'Aurora Tabaco 12', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-13', icon: '/stickers/AuroraTabaco/st1_0003_Layer-4.png', name: 'Aurora Tabaco 13', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-14', icon: '/stickers/AuroraTabaco/st1_0005_Layer-6.png', name: 'Aurora Tabaco 14', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-15', icon: '/stickers/AuroraTabaco/st1_0006_Layer-7.png', name: 'Aurora Tabaco 15', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-16', icon: '/stickers/AuroraTabaco/st1_0009_Layer-10.png', name: 'Aurora Tabaco 16', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-17', icon: '/stickers/AuroraTabaco/st3_0001_Layer-2.png', name: 'Aurora Tabaco 17', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-18', icon: '/stickers/AuroraTabaco/st3_0003_Layer-4.png', name: 'Aurora Tabaco 18', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-19', icon: '/stickers/AuroraTabaco/st_0001_Layer-2.png', name: 'Aurora Tabaco 19', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-20', icon: '/stickers/AuroraTabaco/st_0002_Layer-3.png', name: 'Aurora Tabaco 20', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-21', icon: '/stickers/AuroraTabaco/st_0003_Layer-4.png', name: 'Aurora Tabaco 21', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-22', icon: '/stickers/AuroraTabaco/st_0004_Layer-5.png', name: 'Aurora Tabaco 22', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'auroratabaco-23', icon: '/stickers/AuroraTabaco/st_0006_Layer-7.png', name: 'Aurora Tabaco 23', color: '#8B5A8F', company: 'Aurora Tabaco' },
  { id: 'brickpoint-1', icon: '/stickers/Brickpoint/brickpoint_0000_Capa-2.png', name: 'Brickpoint 1', color: '#E63946', company: 'Brickpoint' },
  { id: 'brickpoint-2', icon: '/stickers/Brickpoint/brickpoint_0001_Capa-3.png', name: 'Brickpoint 2', color: '#E63946', company: 'Brickpoint' },
  { id: 'brickpoint-3', icon: '/stickers/Brickpoint/brickpoint_0002_Capa-1.png', name: 'Brickpoint 3', color: '#E63946', company: 'Brickpoint' },
  { id: 'fidelium-1', icon: '/stickers/Fidelium/american-fidelium-_0000_Capa-2.png', name: 'Fidelium 1', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-2', icon: '/stickers/Fidelium/american-fidelium-_0001_Capa-3.png', name: 'Fidelium 2', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-3', icon: '/stickers/Fidelium/american-fidelium-_0002_Capa-4.png', name: 'Fidelium 3', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-4', icon: '/stickers/Fidelium/american-fidelium-_0003_Capa-5.png', name: 'Fidelium 4', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-5', icon: '/stickers/Fidelium/american-fidelium-_0004_Capa-6.png', name: 'Fidelium 5', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-6', icon: '/stickers/Fidelium/american-fidelium-_0005_Capa-7.png', name: 'Fidelium 6', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-7', icon: '/stickers/Fidelium/american-fidelium-_0006_Capa-8.png', name: 'Fidelium 7', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-8', icon: '/stickers/Fidelium/american-fidelium-_0007_Capa-9.png', name: 'Fidelium 8', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-9', icon: '/stickers/Fidelium/american-fidelium-_0008_Capa-10.png', name: 'Fidelium 9', color: '#06FFA5', company: 'Fidelium' },
  { id: 'fidelium-10', icon: '/stickers/Fidelium/american-fidelium-_0009_Capa-1.png', name: 'Fidelium 10', color: '#06FFA5', company: 'Fidelium' },
  { id: 'grupocoporativo-1', icon: '/stickers/GrupoCoporativo/grupo-coorporativo-stiker_0002_Capa-2.png', name: 'Grupo Coporativo 1', color: '#FFD700', company: 'Grupo Coporativo' },
  { id: 'grupocoporativo-2', icon: '/stickers/GrupoCoporativo/grupo-coorporativo-stiker_0003_Capa-3.png', name: 'Grupo Coporativo 2', color: '#FFD700', company: 'Grupo Coporativo' },
  { id: 'grupocoporativo-3', icon: '/stickers/GrupoCoporativo/grupo-coorporativo-stiker_0004_Capa-4.png', name: 'Grupo Coporativo 3', color: '#FFD700', company: 'Grupo Coporativo' },
  { id: 'grupocoporativo-4', icon: '/stickers/GrupoCoporativo/grupo-coorporativo-stiker_0005_Capa-5.png', name: 'Grupo Coporativo 4', color: '#FFD700', company: 'Grupo Coporativo' },
  { id: 'kora-1', icon: '/stickers/Kora/st1_0001_Layer-2.png', name: 'Kora 1', color: '#FF1493', company: 'Kora' },
  { id: 'kora-2', icon: '/stickers/Kora/st1_0002_Layer-3.png', name: 'Kora 2', color: '#FF1493', company: 'Kora' },
  { id: 'kora-3', icon: '/stickers/Kora/st1_0004_Layer-5.png', name: 'Kora 3', color: '#FF1493', company: 'Kora' },
  { id: 'kora-4', icon: '/stickers/Kora/st1_0007_Layer-8.png', name: 'Kora 4', color: '#FF1493', company: 'Kora' },
  { id: 'kora-5', icon: '/stickers/Kora/st1_0008_Layer-9.png', name: 'Kora 5', color: '#FF1493', company: 'Kora' },
  { id: 'kora-6', icon: '/stickers/Kora/st2_0000_Layer-1.png', name: 'Kora 6', color: '#FF1493', company: 'Kora' },
  { id: 'kora-7', icon: '/stickers/Kora/st2_0001_Layer-2.png', name: 'Kora 7', color: '#FF1493', company: 'Kora' },
  { id: 'kora-8', icon: '/stickers/Kora/st2_0002_Layer-3.png', name: 'Kora 8', color: '#FF1493', company: 'Kora' },
  { id: 'kora-9', icon: '/stickers/Kora/st2_0003_Layer-4.png', name: 'Kora 9', color: '#FF1493', company: 'Kora' },
  { id: 'kora-10', icon: '/stickers/Kora/st2_0004_Layer-5.png', name: 'Kora 10', color: '#FF1493', company: 'Kora' },
  { id: 'kora-11', icon: '/stickers/Kora/st2_0005_Layer-6.png', name: 'Kora 11', color: '#FF1493', company: 'Kora' },
  { id: 'kora-12', icon: '/stickers/Kora/st2_0006_Layer-7.png', name: 'Kora 12', color: '#FF1493', company: 'Kora' },
  { id: 'kora-13', icon: '/stickers/Kora/st2_0007_Layer-8.png', name: 'Kora 13', color: '#FF1493', company: 'Kora' },
  { id: 'kora-14', icon: '/stickers/Kora/st2_0008_Layer-9.png', name: 'Kora 14', color: '#FF1493', company: 'Kora' },
  { id: 'kora-15', icon: '/stickers/Kora/st2_0009_Layer-10.png', name: 'Kora 15', color: '#FF1493', company: 'Kora' },
  { id: 'kora-16', icon: '/stickers/Kora/st3_0000_Layer-1.png', name: 'Kora 16', color: '#FF1493', company: 'Kora' },
  { id: 'kora-17', icon: '/stickers/Kora/st3_0002_Layer-3.png', name: 'Kora 17', color: '#FF1493', company: 'Kora' },
  { id: 'kora-18', icon: '/stickers/Kora/st_0000_Layer-1.png', name: 'Kora 18', color: '#FF1493', company: 'Kora' },
  { id: 'kora-19', icon: '/stickers/Kora/st_0005_Layer-6.png', name: 'Kora 19', color: '#FF1493', company: 'Kora' },
  { id: 'kora-20', icon: '/stickers/Kora/st_0007_Layer-8.png', name: 'Kora 20', color: '#FF1493', company: 'Kora' },
  { id: 'kora-21', icon: '/stickers/Kora/st_0008_Layer-9.png', name: 'Kora 21', color: '#FF1493', company: 'Kora' },
  { id: 'parqueindustrialelj-1', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0000_Capa-1.png', name: 'Parque Industrial E L J 1', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-2', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0001_Capa-2.png', name: 'Parque Industrial E L J 2', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-3', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0002_Capa-3.png', name: 'Parque Industrial E L J 3', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-4', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0003_Capa-4.png', name: 'Parque Industrial E L J 4', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-5', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0004_Capa-5.png', name: 'Parque Industrial E L J 5', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-6', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0005_Capa-6.png', name: 'Parque Industrial E L J 6', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-7', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0006_Capa-7.png', name: 'Parque Industrial E L J 7', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-8', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0007_Capa-8.png', name: 'Parque Industrial E L J 8', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-9', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0008_Capa-9.png', name: 'Parque Industrial E L J 9', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'parqueindustrialelj-10', icon: '/stickers/ParqueIndustrialELJ/parque-industrial-eduardo-leon-jimenez-stiker_0009_Capa-0.png', name: 'Parque Industrial E L J 10', color: '#9370DB', company: 'Parque Industrial E L J' },
  { id: 'patronale-1', icon: '/stickers/Patronale/patronale-stiker_0000_Capa-1.png', name: 'Patronale 1', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-2', icon: '/stickers/Patronale/patronale-stiker_0001_Capa-2.png', name: 'Patronale 2', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-3', icon: '/stickers/Patronale/patronale-stiker_0002_Capa-3.png', name: 'Patronale 3', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-4', icon: '/stickers/Patronale/patronale-stiker_0003_Capa-4.png', name: 'Patronale 4', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-5', icon: '/stickers/Patronale/patronale-stiker_0004_Capa-5.png', name: 'Patronale 5', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-6', icon: '/stickers/Patronale/patronale-stiker_0005_Capa-6.png', name: 'Patronale 6', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-7', icon: '/stickers/Patronale/patronale-stiker_0006_Capa-7.png', name: 'Patronale 7', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-8', icon: '/stickers/Patronale/patronale-stiker_0007_Capa-8.png', name: 'Patronale 8', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-9', icon: '/stickers/Patronale/patronale-stiker_0010_Capa-9.png', name: 'Patronale 9', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-10', icon: '/stickers/Patronale/patronale-stiker_0011_Capa-10.png', name: 'Patronale 10', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-11', icon: '/stickers/Patronale/patronale-stiker_0012_Capa-0.png', name: 'Patronale 11', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-12', icon: '/stickers/Patronale/petronale-2-sticker_0000_Capa-1.png', name: 'Patronale 12', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-13', icon: '/stickers/Patronale/petronale-2-sticker_0001_Capa-2.png', name: 'Patronale 13', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-14', icon: '/stickers/Patronale/petronale-2-sticker_0002_Capa-3.png', name: 'Patronale 14', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-15', icon: '/stickers/Patronale/petronale-2-sticker_0003_Capa-4.png', name: 'Patronale 15', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-16', icon: '/stickers/Patronale/petronale-2-sticker_0004_Capa-5.png', name: 'Patronale 16', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-17', icon: '/stickers/Patronale/petronale-2-sticker_0005_Capa-6.png', name: 'Patronale 17', color: '#FFB347', company: 'Patronale' },
  { id: 'patronale-18', icon: '/stickers/Patronale/petronale-2-sticker_0006_Capa-0.png', name: 'Patronale 18', color: '#FFB347', company: 'Patronale' },
  { id: 'pcm-1', icon: '/stickers/PCM/PCM-stiker_0000_Capa-2.png', name: 'P C M 1', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-2', icon: '/stickers/PCM/PCM-stiker_0001_Capa-3.png', name: 'P C M 2', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-3', icon: '/stickers/PCM/PCM-stiker_0002_Capa-4.png', name: 'P C M 3', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-4', icon: '/stickers/PCM/PCM-stiker_0003_Capa-5.png', name: 'P C M 4', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-5', icon: '/stickers/PCM/PCM-stiker_0004_Capa-6.png', name: 'P C M 5', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-6', icon: '/stickers/PCM/PCM-stiker_0005_Capa-7.png', name: 'P C M 6', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-7', icon: '/stickers/PCM/PCM-stiker_0006_Capa-8.png', name: 'P C M 7', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-8', icon: '/stickers/PCM/PCM-stiker_0007_Capa-9.png', name: 'P C M 8', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-9', icon: '/stickers/PCM/PCM-stiker_0008_Capa-10.png', name: 'P C M 9', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-10', icon: '/stickers/PCM/PCM-stiker_0009_Capa-11.png', name: 'P C M 10', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-11', icon: '/stickers/PCM/PCM-stiker_0010_Capa-0.png', name: 'P C M 11', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-12', icon: '/stickers/PCM/PCM-stiker_0011_Capa-1.png', name: 'P C M 12', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-13', icon: '/stickers/PCM/PCM_0000_Capa-2.png', name: 'P C M 13', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-14', icon: '/stickers/PCM/PCM_0003_Capa-0.png', name: 'P C M 14', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-15', icon: '/stickers/PCM/PCM_0004_Capa-1.png', name: 'P C M 15', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-16', icon: '/stickers/PCM/pcm_0001_Capa-3.png', name: 'P C M 16', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-17', icon: '/stickers/PCM/pcm_0002_Capa-4.png', name: 'P C M 17', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-18', icon: '/stickers/PCM/pcm_0003_Capa-5.png', name: 'P C M 18', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-19', icon: '/stickers/PCM/pcm_0004_Capa-6.png', name: 'P C M 19', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-20', icon: '/stickers/PCM/pcm_0005_Capa-7.png', name: 'P C M 20', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-21', icon: '/stickers/PCM/pcm_0006_Capa-8.png', name: 'P C M 21', color: '#00CED1', company: 'P C M' },
  { id: 'pcm-22', icon: '/stickers/PCM/pcm_0007_Capa-1.png', name: 'P C M 22', color: '#00CED1', company: 'P C M' },
  { id: 'rum-1', icon: '/stickers/Rum/rum.png', name: 'Rum 1', color: '#FFA500', company: 'Rum' },
  { id: 'rum-2', icon: '/stickers/Rum/rum2.png', name: 'Rum 2', color: '#FFA500', company: 'Rum' },
  { id: 'rum-3', icon: '/stickers/Rum/rum3.png', name: 'Rum 3', color: '#FFA500', company: 'Rum' },
  { id: 'rum-4', icon: '/stickers/Rum/rum4.png', name: 'Rum 4', color: '#FFA500', company: 'Rum' },
  { id: 'sunriseinternational-1', icon: '/stickers/SunriseInternational/sunrise-internationañ_0000_Capa-2.png', name: 'Sunrise International 1', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-2', icon: '/stickers/SunriseInternational/sunrise-internationañ_0001_Capa-3.png', name: 'Sunrise International 2', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-3', icon: '/stickers/SunriseInternational/sunrise-internationañ_0002_Capa-4.png', name: 'Sunrise International 3', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-4', icon: '/stickers/SunriseInternational/sunrise-internationañ_0003_Capa-5.png', name: 'Sunrise International 4', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-5', icon: '/stickers/SunriseInternational/sunrise-internationañ_0004_Capa-6.png', name: 'Sunrise International 5', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-6', icon: '/stickers/SunriseInternational/sunrise-internationañ_0005_Capa-7.png', name: 'Sunrise International 6', color: '#FF69B4', company: 'Sunrise International' },
  { id: 'sunriseinternational-7', icon: '/stickers/SunriseInternational/sunrise-internationañ_0006_Capa-1.png', name: 'Sunrise International 7', color: '#FF69B4', company: 'Sunrise International' },
];

/**
 * List of all companies
 */
export const COMPANIES: string[] = [
  'Aurora Global',
  'Aurora Logistic',
  'Aurora Tabaco',
  'Brickpoint',
  'Fidelium',
  'Grupo Coporativo',
  'Kora',
  'P C M',
  'Parque Industrial E L J',
  'Patronale',
  'Rum',
  'Sunrise International',
  'aurora usa stiker',
];

/**
 * Get stickers by company
 */
export function getStickersByCompany(company: string): Sticker[] {
  return AVAILABLE_STICKERS.filter(s => s.company === company);
}

/**
 * Get company color
 */
export function getCompanyColor(company: string): string {
  const sticker = AVAILABLE_STICKERS.find(s => s.company === company);
  return sticker?.color || '#FF6B35';
}
